/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_CpuTempMeter
#define HEADER_CpuTempMeter
/*
htop - CpuTempMeter.h
(C) 2020 @lex
*/

#include "Meter.h"

extern int CpuTempMeter_attributes[];

extern MeterClass CpuTempMeter_class;

extern int CoreTempMeter_attributes[];

extern MeterClass CoreTempMeter_class;

#endif
